app:
    resource: '@AppBundle/Controller/Frontend/'
    type: annotation
    prefix: /e-learning/
app_admin:
    resource: '@AppBundle/Controller/Backend/'
    type: annotation
    prefix: /wp-admin/e-learning/

ekino_wordpress:
    resource: "@EkinoWordpressBundle/Resources/config/routing.xml"