<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Asset;
use AppBundle\Entity\Course;
use AppBundle\Entity\CourseOption;

/**
 * AssetRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Course $course
     * @return Asset[]
     */
    public function findByCourse(Course $course)
    {
        $assets = [];
        /** @var CourseOption $courseOption */
        foreach ($course->getCourseOptions() as $courseOption) {
            foreach ($courseOption->getAssets() as $asset) {
                $assets[] = $asset;
            }
        }

        return $assets;
    }
}
