<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Course;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * AssetParticipantRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssetParticipantRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLearnedAssetsInCourse(Course $course, UserInterface $user)
    {
        return $this->findBy([
            'username' => $user->getUsername(),
            'courseId' => $course->getId(),
        ]);
    }
}
