<?php

namespace AppBundle\Repository;

/**
 * AzureAccessPolicyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AzureAccessPolicyRepository extends \Doctrine\ORM\EntityRepository
{
}
