<?php

namespace AppBundle\Repository;

/**
 * CourseRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getCourseListQueryBuilder()
    {
        return $this->createQueryBuilder('c')
            ->select('c.id, c.sku, c.name, c.image, c.description, c.shortDescription,
                COUNT(cp.username) as totalParticipant'
            )
            ->leftJoin('AppBundle:CourseParticipant', 'cp', 'WITH', 'cp.course=c.id')
            ->groupBy('c.id');
    }
}
