<?php

namespace AppBundle\Repository;

/**
 * CourseOptionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
