<?php

namespace AppBundle\Repository;

/**
 * CourseParticipantRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CourseParticipantRepository extends \Doctrine\ORM\EntityRepository
{
}
